# Generated by Django 5.0.1 on 2024-03-08 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category_postcat',
            field=models.ManyToManyField(related_name='posts', through='news.PostCategory', to='news.category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
